CC=gcc-9.1.0
CCFLAG= -std=c18 -g -Wall -Wextra -Wpedantic -Wno-unused-variable -DDEBUG
LDFLAG= 

output: main.o
	$CC $LDFLAG -o out main.o

main.o: main.c
	$CC $CCFLAG -c main.c

cl:
	rm *.o
nk:	cl
	rm out

# vim: set ft=make:
